version: "3.9"
#OVERRIDE ENV WITH SECRETS AT DEPLOY STAGE
services:
  web:
    build: .
    ports:
      - 8010:8010
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=example
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ENV_NAME=local
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: example    
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - 5434:5432